"""Agrega imagen_path a movimientos

Revision ID: 11da95d43807
Revises: 0c1cea6baa10
Create Date: 2025-04-27 21:16:18.513680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '11da95d43807'
down_revision: Union[str, None] = '0c1cea6baa10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicion', sa.Column('anguloMin', sa.Float(), nullable=True))
    op.add_column('medicion', sa.Column('angulaMax', sa.Float(), nullable=True))
    op.drop_index('ix_medicion_anguloReal', table_name='medicion')
    op.create_index(op.f('ix_medicion_angulaMax'), 'medicion', ['angulaMax'], unique=False)
    op.create_index(op.f('ix_medicion_anguloMin'), 'medicion', ['anguloMin'], unique=False)
    op.drop_column('medicion', 'anguloReal')
    op.add_column('movimiento', sa.Column('anguloMinReal', sa.Float(), nullable=True))
    op.add_column('movimiento', sa.Column('angulaMaxReal', sa.Float(), nullable=True))
    op.add_column('movimiento', sa.Column('imagen_path', sa.String(length=255), nullable=True))
    op.drop_index('ix_movimiento_angulaMax', table_name='movimiento')
    op.drop_index('ix_movimiento_anguloMin', table_name='movimiento')
    op.create_index(op.f('ix_movimiento_angulaMaxReal'), 'movimiento', ['angulaMaxReal'], unique=False)
    op.create_index(op.f('ix_movimiento_anguloMinReal'), 'movimiento', ['anguloMinReal'], unique=False)
    op.drop_column('movimiento', 'anguloMin')
    op.drop_column('movimiento', 'angulaMax')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movimiento', sa.Column('angulaMax', mysql.FLOAT(), nullable=True))
    op.add_column('movimiento', sa.Column('anguloMin', mysql.FLOAT(), nullable=True))
    op.drop_index(op.f('ix_movimiento_anguloMinReal'), table_name='movimiento')
    op.drop_index(op.f('ix_movimiento_angulaMaxReal'), table_name='movimiento')
    op.create_index('ix_movimiento_anguloMin', 'movimiento', ['anguloMin'], unique=False)
    op.create_index('ix_movimiento_angulaMax', 'movimiento', ['angulaMax'], unique=False)
    op.drop_column('movimiento', 'imagen_path')
    op.drop_column('movimiento', 'angulaMaxReal')
    op.drop_column('movimiento', 'anguloMinReal')
    op.add_column('medicion', sa.Column('anguloReal', mysql.FLOAT(), nullable=True))
    op.drop_index(op.f('ix_medicion_anguloMin'), table_name='medicion')
    op.drop_index(op.f('ix_medicion_angulaMax'), table_name='medicion')
    op.create_index('ix_medicion_anguloReal', 'medicion', ['anguloReal'], unique=False)
    op.drop_column('medicion', 'angulaMax')
    op.drop_column('medicion', 'anguloMin')
    # ### end Alembic commands ###
