"""update5

Revision ID: 4bab301579cc
Revises: 95d6b0a14f23
Create Date: 2025-06-15 18:20:09.311269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bab301579cc'
down_revision: Union[str, None] = '95d6b0a14f23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paciente', sa.Column('profesionalId', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_paciente_profesionalId'), 'paciente', ['profesionalId'], unique=False)
    op.create_foreign_key(None, 'paciente', 'profesional', ['profesionalId'], ['profesionalId'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'paciente', type_='foreignkey')
    op.drop_index(op.f('ix_paciente_profesionalId'), table_name='paciente')
    op.drop_column('paciente', 'profesionalId')
    # ### end Alembic commands ###
