"""agregar lado

Revision ID: 4cdad439fca7
Revises: 1546d4158732
Create Date: 2025-05-17 19:01:29.794789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cdad439fca7'
down_revision: Union[str, None] = '1546d4158732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicion', sa.Column('lado', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_medicion_lado'), 'medicion', ['lado'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medicion_lado'), table_name='medicion')
    op.drop_column('medicion', 'lado')
    # ### end Alembic commands ###
