"""update3

Revision ID: 6d3a94ae6f5f
Revises: e99dc6bb4a56
Create Date: 2025-06-03 17:01:00.897576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d3a94ae6f5f'
down_revision: Union[str, None] = 'e99dc6bb4a56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_profesional_especialidad', table_name='profesional')
    op.create_index(op.f('ix_profesional_especialidad'), 'profesional', ['especialidad'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profesional_especialidad'), table_name='profesional')
    op.create_index('ix_profesional_especialidad', 'profesional', ['especialidad'], unique=True)
    # ### end Alembic commands ###
