"""ajustes de nombre

Revision ID: 83cbb3726a5e
Revises: 11da95d43807
Create Date: 2025-05-06 14:55:56.590800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '83cbb3726a5e'
down_revision: Union[str, None] = '11da95d43807'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicion', sa.Column('anguloMax', sa.Float(), nullable=True))
    op.drop_index('ix_medicion_angulaMax', table_name='medicion')
    op.create_index(op.f('ix_medicion_anguloMax'), 'medicion', ['anguloMax'], unique=False)
    op.drop_column('medicion', 'angulaMax')
    op.add_column('movimiento', sa.Column('anguloMaxReal', sa.Float(), nullable=True))
    op.drop_index('ix_movimiento_angulaMaxReal', table_name='movimiento')
    op.create_index(op.f('ix_movimiento_anguloMaxReal'), 'movimiento', ['anguloMaxReal'], unique=False)
    op.drop_column('movimiento', 'angulaMaxReal')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movimiento', sa.Column('angulaMaxReal', mysql.FLOAT(), nullable=True))
    op.drop_index(op.f('ix_movimiento_anguloMaxReal'), table_name='movimiento')
    op.create_index('ix_movimiento_angulaMaxReal', 'movimiento', ['angulaMaxReal'], unique=False)
    op.drop_column('movimiento', 'anguloMaxReal')
    op.add_column('medicion', sa.Column('angulaMax', mysql.FLOAT(), nullable=True))
    op.drop_index(op.f('ix_medicion_anguloMax'), table_name='medicion')
    op.create_index('ix_medicion_angulaMax', 'medicion', ['angulaMax'], unique=False)
    op.drop_column('medicion', 'anguloMax')
    # ### end Alembic commands ###
