"""update4

Revision ID: 95d6b0a14f23
Revises: 6d3a94ae6f5f
Create Date: 2025-06-10 17:12:05.354104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95d6b0a14f23'
down_revision: Union[str, None] = '6d3a94ae6f5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paciente', sa.Column('genero', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_paciente_genero'), 'paciente', ['genero'], unique=False)
    op.drop_index('ix_usuario_correo', table_name='usuario')
    op.create_index(op.f('ix_usuario_correo'), 'usuario', ['correo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuario_correo'), table_name='usuario')
    op.create_index('ix_usuario_correo', 'usuario', ['correo'], unique=True)
    op.drop_index(op.f('ix_paciente_genero'), table_name='paciente')
    op.drop_column('paciente', 'genero')
    # ### end Alembic commands ###
