"""Agrega imagen_path a articulacion

Revision ID: de975194aaf0
Revises: ca49352a76cd
Create Date: 2025-04-26 16:51:23.945179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'de975194aaf0'
down_revision: Union[str, None] = 'ca49352a76cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('articulacion', sa.Column('nombre', sa.String(length=30), nullable=True))
    op.add_column('articulacion', sa.Column('imagen_path', sa.String(length=255), nullable=True))
    op.drop_index('ix_articulacion_especialidad', table_name='articulacion')
    op.create_index(op.f('ix_articulacion_nombre'), 'articulacion', ['nombre'], unique=False)
    op.drop_column('articulacion', 'especialidad')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articulacion', sa.Column('especialidad', mysql.VARCHAR(length=30), nullable=True))
    op.drop_index(op.f('ix_articulacion_nombre'), table_name='articulacion')
    op.create_index('ix_articulacion_especialidad', 'articulacion', ['especialidad'], unique=False)
    op.drop_column('articulacion', 'imagen_path')
    op.drop_column('articulacion', 'nombre')
    # ### end Alembic commands ###
