"""initial

Revision ID: e48544b4d807
Revises: 
Create Date: 2025-06-03 23:05:57.056662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e48544b4d807'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articulacion',
    sa.Column('articulacionId', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=True),
    sa.Column('imagen_path', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('articulacionId')
    )
    op.create_index(op.f('ix_articulacion_articulacionId'), 'articulacion', ['articulacionId'], unique=False)
    op.create_index(op.f('ix_articulacion_nombre'), 'articulacion', ['nombre'], unique=False)
    op.create_table('usuario',
    sa.Column('usuarioId', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=300), nullable=True),
    sa.Column('correo', sa.String(length=200), nullable=True),
    sa.Column('contrasena', sa.String(length=30), nullable=True),
    sa.Column('rol', sa.String(length=30), nullable=True),
    sa.Column('rut', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('usuarioId')
    )
    op.create_index(op.f('ix_usuario_contrasena'), 'usuario', ['contrasena'], unique=False)
    op.create_index(op.f('ix_usuario_correo'), 'usuario', ['correo'], unique=True)
    op.create_index(op.f('ix_usuario_nombre'), 'usuario', ['nombre'], unique=False)
    op.create_index(op.f('ix_usuario_rol'), 'usuario', ['rol'], unique=False)
    op.create_index(op.f('ix_usuario_rut'), 'usuario', ['rut'], unique=True)
    op.create_index(op.f('ix_usuario_usuarioId'), 'usuario', ['usuarioId'], unique=False)
    op.create_table('movimiento',
    sa.Column('movimientoId', sa.Integer(), nullable=False),
    sa.Column('ArticulacionId', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('anguloMinReal', sa.Float(), nullable=True),
    sa.Column('anguloMaxReal', sa.Float(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('imagen_path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['ArticulacionId'], ['articulacion.articulacionId'], ),
    sa.PrimaryKeyConstraint('movimientoId')
    )
    op.create_index(op.f('ix_movimiento_ArticulacionId'), 'movimiento', ['ArticulacionId'], unique=False)
    op.create_index(op.f('ix_movimiento_anguloMaxReal'), 'movimiento', ['anguloMaxReal'], unique=False)
    op.create_index(op.f('ix_movimiento_anguloMinReal'), 'movimiento', ['anguloMinReal'], unique=False)
    op.create_index(op.f('ix_movimiento_movimientoId'), 'movimiento', ['movimientoId'], unique=False)
    op.create_index(op.f('ix_movimiento_nombre'), 'movimiento', ['nombre'], unique=False)
    op.create_table('paciente',
    sa.Column('pacienteId', sa.Integer(), nullable=False),
    sa.Column('usuarioId', sa.Integer(), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('telefono', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuarioId'], ['usuario.usuarioId'], ),
    sa.PrimaryKeyConstraint('pacienteId')
    )
    op.create_index(op.f('ix_paciente_edad'), 'paciente', ['edad'], unique=False)
    op.create_index(op.f('ix_paciente_pacienteId'), 'paciente', ['pacienteId'], unique=False)
    op.create_index(op.f('ix_paciente_telefono'), 'paciente', ['telefono'], unique=False)
    op.create_index(op.f('ix_paciente_usuarioId'), 'paciente', ['usuarioId'], unique=False)
    op.create_table('profesional',
    sa.Column('profesionalId', sa.Integer(), nullable=False),
    sa.Column('usuarioId', sa.Integer(), nullable=True),
    sa.Column('especialidad', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['usuarioId'], ['usuario.usuarioId'], ),
    sa.PrimaryKeyConstraint('profesionalId')
    )
    op.create_index(op.f('ix_profesional_especialidad'), 'profesional', ['especialidad'], unique=False)
    op.create_index(op.f('ix_profesional_profesionalId'), 'profesional', ['profesionalId'], unique=False)
    op.create_index(op.f('ix_profesional_usuarioId'), 'profesional', ['usuarioId'], unique=False)
    op.create_table('ejercicio',
    sa.Column('ejercicioId', sa.Integer(), nullable=False),
    sa.Column('MovimientoId', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['MovimientoId'], ['movimiento.movimientoId'], ),
    sa.PrimaryKeyConstraint('ejercicioId')
    )
    op.create_index(op.f('ix_ejercicio_MovimientoId'), 'ejercicio', ['MovimientoId'], unique=False)
    op.create_index(op.f('ix_ejercicio_ejercicioId'), 'ejercicio', ['ejercicioId'], unique=False)
    op.create_index(op.f('ix_ejercicio_nombre'), 'ejercicio', ['nombre'], unique=False)
    op.create_table('sesion',
    sa.Column('sesionId', sa.Integer(), nullable=False),
    sa.Column('PacienteId', sa.Integer(), nullable=True),
    sa.Column('ProfesionalId', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('hora', sa.Time(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['PacienteId'], ['paciente.pacienteId'], ),
    sa.ForeignKeyConstraint(['ProfesionalId'], ['profesional.profesionalId'], ),
    sa.PrimaryKeyConstraint('sesionId')
    )
    op.create_index(op.f('ix_sesion_PacienteId'), 'sesion', ['PacienteId'], unique=False)
    op.create_index(op.f('ix_sesion_ProfesionalId'), 'sesion', ['ProfesionalId'], unique=False)
    op.create_index(op.f('ix_sesion_fecha'), 'sesion', ['fecha'], unique=False)
    op.create_index(op.f('ix_sesion_hora'), 'sesion', ['hora'], unique=False)
    op.create_index(op.f('ix_sesion_sesionId'), 'sesion', ['sesionId'], unique=False)
    op.create_table('medicion',
    sa.Column('medicionId', sa.Integer(), nullable=False),
    sa.Column('SesionId', sa.Integer(), nullable=True),
    sa.Column('EjercicioId', sa.Integer(), nullable=True),
    sa.Column('MovimientoId', sa.Integer(), nullable=True),
    sa.Column('anguloMin', sa.Float(), nullable=True),
    sa.Column('anguloMax', sa.Float(), nullable=True),
    sa.Column('lado', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['EjercicioId'], ['ejercicio.ejercicioId'], ),
    sa.ForeignKeyConstraint(['MovimientoId'], ['movimiento.movimientoId'], ),
    sa.ForeignKeyConstraint(['SesionId'], ['sesion.sesionId'], ),
    sa.PrimaryKeyConstraint('medicionId')
    )
    op.create_index(op.f('ix_medicion_EjercicioId'), 'medicion', ['EjercicioId'], unique=False)
    op.create_index(op.f('ix_medicion_MovimientoId'), 'medicion', ['MovimientoId'], unique=False)
    op.create_index(op.f('ix_medicion_SesionId'), 'medicion', ['SesionId'], unique=False)
    op.create_index(op.f('ix_medicion_anguloMax'), 'medicion', ['anguloMax'], unique=False)
    op.create_index(op.f('ix_medicion_anguloMin'), 'medicion', ['anguloMin'], unique=False)
    op.create_index(op.f('ix_medicion_lado'), 'medicion', ['lado'], unique=False)
    op.create_index(op.f('ix_medicion_medicionId'), 'medicion', ['medicionId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medicion_medicionId'), table_name='medicion')
    op.drop_index(op.f('ix_medicion_lado'), table_name='medicion')
    op.drop_index(op.f('ix_medicion_anguloMin'), table_name='medicion')
    op.drop_index(op.f('ix_medicion_anguloMax'), table_name='medicion')
    op.drop_index(op.f('ix_medicion_SesionId'), table_name='medicion')
    op.drop_index(op.f('ix_medicion_MovimientoId'), table_name='medicion')
    op.drop_index(op.f('ix_medicion_EjercicioId'), table_name='medicion')
    op.drop_table('medicion')
    op.drop_index(op.f('ix_sesion_sesionId'), table_name='sesion')
    op.drop_index(op.f('ix_sesion_hora'), table_name='sesion')
    op.drop_index(op.f('ix_sesion_fecha'), table_name='sesion')
    op.drop_index(op.f('ix_sesion_ProfesionalId'), table_name='sesion')
    op.drop_index(op.f('ix_sesion_PacienteId'), table_name='sesion')
    op.drop_table('sesion')
    op.drop_index(op.f('ix_ejercicio_nombre'), table_name='ejercicio')
    op.drop_index(op.f('ix_ejercicio_ejercicioId'), table_name='ejercicio')
    op.drop_index(op.f('ix_ejercicio_MovimientoId'), table_name='ejercicio')
    op.drop_table('ejercicio')
    op.drop_index(op.f('ix_profesional_usuarioId'), table_name='profesional')
    op.drop_index(op.f('ix_profesional_profesionalId'), table_name='profesional')
    op.drop_index(op.f('ix_profesional_especialidad'), table_name='profesional')
    op.drop_table('profesional')
    op.drop_index(op.f('ix_paciente_usuarioId'), table_name='paciente')
    op.drop_index(op.f('ix_paciente_telefono'), table_name='paciente')
    op.drop_index(op.f('ix_paciente_pacienteId'), table_name='paciente')
    op.drop_index(op.f('ix_paciente_edad'), table_name='paciente')
    op.drop_table('paciente')
    op.drop_index(op.f('ix_movimiento_nombre'), table_name='movimiento')
    op.drop_index(op.f('ix_movimiento_movimientoId'), table_name='movimiento')
    op.drop_index(op.f('ix_movimiento_anguloMinReal'), table_name='movimiento')
    op.drop_index(op.f('ix_movimiento_anguloMaxReal'), table_name='movimiento')
    op.drop_index(op.f('ix_movimiento_ArticulacionId'), table_name='movimiento')
    op.drop_table('movimiento')
    op.drop_index(op.f('ix_usuario_usuarioId'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_rut'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_rol'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_nombre'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_correo'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_contrasena'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_articulacion_nombre'), table_name='articulacion')
    op.drop_index(op.f('ix_articulacion_articulacionId'), table_name='articulacion')
    op.drop_table('articulacion')
    # ### end Alembic commands ###
