"""update

Revision ID: ee096e45ad50
Revises: 4cdad439fca7
Create Date: 2025-05-25 21:17:27.016163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee096e45ad50'
down_revision: Union[str, None] = '4cdad439fca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_medicion_fecha', table_name='medicion')
    op.drop_column('medicion', 'fecha')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicion', sa.Column('fecha', sa.DATE(), nullable=True))
    op.create_index('ix_medicion_fecha', 'medicion', ['fecha'], unique=False)
    # ### end Alembic commands ###
